#!/usr/bin/env ruby
# frozen_string_literal: true

# rubocop:disable Metrics/ClassLength
# rubocop:disable Metrics/MethodLength
# rubocop:disable Style/Documentation

# chmod +x $HOME/git_stats

require 'optparse'

class GitStats
  attr_reader :options
  attr_accessor :contributors

  def initialize
    @contributors = {}
    @options = define_options
  end

  def report
    contributions
    min_author_width
    author_output
    final_output
  end

  def contributions
    git_combined_logs.each do |entry|
      author = /.*(?=\n)/.match(entry)[0]
      commit = /(\d+) file/.match(entry)
      insertions = /(\d+) insertion.*/.match(entry)
      deletions = /(\d+) deletion.*/.match(entry)

      contributors[author] ||= {
        commits: 0,
        inserts: 0,
        deletes: 0
      }

      contributors[author][:commits] += 1 if commit
      contributors[author][:inserts] += insertions[1].to_i if insertions
      contributors[author][:deletes] += deletions[1].to_i if deletions
    end

    contributors.each do |_author, hash|
      hash[:total] = hash[:inserts].to_i + hash[:deletes].to_i
      hash[:diff] = hash[:inserts].to_i - hash[:deletes].to_i
      hash[:deletion_percent] = (hash[:deletes].fdiv(hash[:total]) * 100).round(2)
      hash[:addition_percent] = (hash[:inserts].fdiv(hash[:total]) * 100).round(2)
    end
  end

  def author_output
    contributors.transform_keys! { |key| key.strip.downcase }

    horizontal_line

    $stdout.puts(
      format(
        puts_format,
        {
          author: 'author',
          commits: 'commits',
          inserts: 'inserts',
          deletes: 'deletes',
          total: 'total',
          diff: 'diff',
          deletion_percent: 'delete %',
          addition_percent: 'insert %'
        }
      )
    )

    horizontal_line

    if options[:sort] == :author
      contributors.sort_by { |author, _hash| author }.each do |author, hash|
        $stdout.puts(
          format(
            puts_format,
            {
              author: author,
              commits: num_with_separator(hash[:commits]),
              inserts: num_with_separator(hash[:inserts]),
              deletes: num_with_separator(hash[:deletes]),
              total: num_with_separator(hash[:total]),
              diff: num_with_separator(hash[:diff]),
              deletion_percent: hash[:deletion_percent],
              addition_percent: hash[:addition_percent]
            }
          )
        )
      end
    else
      contributors.sort_by { |_author, hash| hash[options[:sort]] }.reverse_each do |author, hash|
        $stdout.puts(
          format(
            puts_format,
            {
              author: author,
              commits: num_with_separator(hash[:commits]),
              inserts: num_with_separator(hash[:inserts]),
              deletes: num_with_separator(hash[:deletes]),
              total: num_with_separator(hash[:total]),
              diff: num_with_separator(hash[:diff]),
              deletion_percent: hash[:deletion_percent],
              addition_percent: hash[:addition_percent]
            }
          )
        )
      end
    end
  end

  def final_output
    total = contributors.map { |_author, hash| hash[:total] }.sum
    all_deletes = contributors.map { |_author, hash| hash[:deletes] }.sum
    all_inserts = contributors.map { |_author, hash| hash[:inserts] }.sum

    horizontal_line

    $stdout.puts(
      format(
        puts_format,
        {
          author: "#{contributors.size} authors",
          commits: num_with_separator(contributors.map { |_author, hash| hash[:commits] }.sum),
          inserts: num_with_separator(all_inserts),
          deletes: num_with_separator(all_deletes),
          diff: num_with_separator(contributors.map { |_author, hash| hash[:diff] }.sum),
          total: num_with_separator(contributors.map { |_author, hash| hash[:total] }.sum),
          deletion_percent: (all_deletes.fdiv(total) * 100).round(2),
          addition_percent: (all_inserts.fdiv(total) * 100).round(2)
        }
      )
    )

    horizontal_line
  end

  private

  def define_options(args: ::ARGV)
    options = {
      sort: :commits,
      group_by: 'ae' # author email
    }

    ::OptionParser.new do |opts|
      opts.banner = <<~MESSAGE
        Usage:
          * via executable: git_stats [options]
          * via ruby: ruby git_stats [options]
        Options:
          * = default
      MESSAGE

      opts.on('-g', '--group-by [GROUP]', 'Author: name, email*') do |opt|
        options[:group_by] = opt.to_sym == :name ? 'an' : 'ae'
      end

      opts.on('-S', '--sort [SORT]', 'Descending: inserts, deletes, total, diff, author, commits*') do |opt|
        options[:sort] = opt.to_sym
      end

      opts.on('-s', '--start-date [DATE]', 'Commits starting on') do |opt|
        options[:start_date] = opt
      end

      opts.on('-e', '--end-date [DATE]', 'Commits ending on') do |opt|
        options[:end_date] = opt
      end
    end.parse!(args)

    options
  rescue ::OptionParser::InvalidOption => e
    warn e.message
    warn 'For usage information, use --help'
    exit 0
  end

  # ------------------------------------------------------------
  #
  # git methods
  #
  # ------------------------------------------------------------

  def directory_repos
    repo_paths = []

    repo_paths << ::Dir.pwd if repository?

    ::Dir.foreach(::Dir.pwd) do |entry|
      next if ['.', '..'].include?(entry)

      path = ::File.join(::Dir.pwd, entry)
      repo_paths << path if ::File.directory?(path) && ::Dir.exist?(::File.join(path, '.git'))
    end

    repo_paths
  end

  def git_combined_logs
    combined_logs = []

    directory_repos.each do |repo_path|
      combined_logs += git_log_entries(repo_path: repo_path)
    end

    combined_logs
  end

  def git_log_entries(repo_path: ::Dir.pwd)
    base = "git -C #{repo_path} log --shortstat --no-merges --pretty=format:%#{options[:group_by]}"
    base += " --since=#{options[:start_date]}" if options[:start_date]
    base += " --until=#{options[:end_date]}" if options[:end_date]

    git_logs = `#{base}`
    git_logs.split(/\n{2}/)
  end

  def repository?
    system('git rev-parse --is-inside-work-tree > /dev/null 2>&1')
  end

  # ------------------------------------------------------------
  #
  # output methods
  #
  # ------------------------------------------------------------

  def min_author_width
    @min_author_width ||= contributors.keys.max_by(&:length)&.size.to_i + 2
  end

  def horizontal_line
    $stdout.puts '-' * (@min_author_width + 77)
  end

  def puts_format
    "%<author>-#{@min_author_width}s " \
      '%<commits>-10s ' \
      '+%<inserts>-10s -%<deletes>-10s ' \
      '%<diff>-10s %<total>-10s ' \
      '%<deletion_percent>-10s %<addition_percent>-10s'
  end

  def num_with_separator(number, separator: ',')
    number.to_s.reverse.scan(/\d{1,3}/).join(separator).reverse
  end
end

GitStats.new.report

# rubocop:enable Metrics/ClassLength
# rubocop:enable Metrics/MethodLength
# rubocop:enable Style/Documentation
